---
apiVersion: v1
kind: Namespace
metadata:
  name: meet
---
apiVersion: v1
kind: Service
metadata:
  namespace: meet
  name: meet
spec:
  selector:
    app: meet
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meet
  name: meet
  labels:
    app: meet
spec:
  selector:
    matchLabels:
      app: meet
  template:
    metadata:
      labels:
        app: meet
    spec:
      containers:
        - name: meet
          image: julia/redirect:v0.0.9
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: meet
  name: meet-julrun
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: https
spec:
  tls:
    - hosts:
      - meet.jul.run
      secretName: meet-julrun-https-cert
  rules:
    - host: meet.jul.run
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: meet
                port:
                  name: http
